=== pippuri/whim-bot/schemas/v1/profile.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "https://api.maas.global/v1/profile",
  "description": "MaaS user profiles",
  "type": "object",
  "properties": {
    "identityId": {
      "$ref": "aws.json#definitions/cognitoIdentityId"
    },
    "plans": {
      "type": "array",
      "items": {
        "$ref": "package.json#definitions/plan"
      }
    },
    "favoriteLocations": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/favoriteLocation"
      }
    },
    "balance": {
      "type": "number"
    },
    "phone": {
      "$ref": "units.json#definitions/phone"
    },
    "email": {
      "$ref": "units.json#definitions/email"
    }
  },
  "additionalProperties": false,
  "required": [ "plans", "favoriteLocations", "balance", "phone", "email" ],
  "definitions": {
    "favoriteLocation": {
      "type": "object",
      "properties": {
        "name":{
          "type": "string",
          "required": true
        },
        "address":{
          "type": "string",
          "required": true
        },
        "lat":{
          "$ref": "units.json#definitions/latitude"
        },
        "lon":{
          "$ref": "units.json#definitions/latitude"
        }
      }
    }
  }
}

=== pippuri/whim-bot/lib/service-bus/mockDynamoProfiles.json
[
  {  
    "plans":[  
      {  
        "id":"payg",
        "invoiceName":"Pay as You Go",
        "price":0,
        "pointGrant":0,
        "formattedPrice":"EUR0",
        "name":"Pay-As-You-Go",
        "chargeModel":"flat_fee",
        "provider":[  
          {  
            "icon":"https://google.com/image/gimmesomething",
            "desc":"Pay with points",
            "name":"taxi"
          },
          {  
            "icon":"https://google.com/image/gimmesomething",
            "desc":"Pay with points",
            "name":"uber"
          },
          {  
            "icon":"https://google.com/image/gimmesomething",
            "desc":"Pay with points",
            "name":"chopper"
          }
        ],
        "feature":[  

        ],
        "period":1,
        "periodUnit":"month",
        "currency":"EUR"
      }
    ],
    "balance":0,
    "phone":"10983012",
    "favoriteLocations":[  
      {  
        "lon":231232,
        "address":"Great Chott salt flat, Tatooine",
        "name":"work",
        "lat":123123
      },
      {  
        "lon":231232,
        "address":"Great Chott salt flat, Tatooine",
        "name":"somewhere",
        "lat":123123
      }
    ],
    "email":"abcd@gmail.com",
    "identityId":"eu-west-1:00000000-cafe-cafe-cafe-000000000000"
  }
]
